#!/usr/bin/env python3
"""Build per-dataset LaTeX longtable snippets and a cross-dataset summary
from the Framework D dominant-axis JSONs produced by
``scripts/eval_round4_dominant_axis.py --tag <ROUND>``.

Inputs (read):
  results/v2_adult_ROUND5/dominant_axis_audit.json
  results/v2_hmda_ROUND5/dominant_axis_audit.json
  results/v2_diabetes_ROUND7/dominant_axis_audit.json

Outputs (write):
  results/V2_DOMINANT_AXIS_LATEST_SUMMARY.md
  paper-body/tables/adult_full_results_round5.tex
  paper-body/tables/hmda_full_results_round5.tex
  paper-body/tables/diabetes_full_results_round7.tex
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
TABLES_DIR = ROOT / "paper-body" / "tables"

INPUTS = [
    {"dataset": "adult", "display": "Adult",
     "tag": "ROUND5", "tex_name": "adult_full_results_round5.tex"},
    {"dataset": "hmda", "display": "HMDA",
     "tag": "ROUND5", "tex_name": "hmda_full_results_round5.tex"},
    {"dataset": "diabetes", "display": "Diabetes",
     "tag": "ROUND7", "tex_name": "diabetes_full_results_round7.tex"},
]


def _escape(s: str) -> str:
    return s.replace("_", r"\_")


def _fmt(x: float, places: int = 4) -> str:
    return f"{x:.{places}f}"


def _fmt_signed(x: float, places: int = 4) -> str:
    return f"{x:+.{places}f}"


def load_dataset(dataset: str, tag: str) -> dict:
    path = ROOT / "results" / f"v2_{dataset}_{tag}" / "dominant_axis_audit.json"
    if not path.exists():
        raise SystemExit(f"missing {path}")
    return json.loads(path.read_text())


def aggregate(per_seed: dict) -> dict:
    rows = []
    for s in per_seed:
        rows.extend(per_seed[s]["rows"])
    multi = [r for r in rows if r["is_multiclass"]]

    def _arr(rs, key):
        return np.array([r[key] for r in rs], dtype=np.float64)

    out = {
        "n_pair_seeds": len(rows),
        "n_multi": len(multi),
        "mean_r2_onehot": float(_arr(rows, "r2_onehot").mean()) if rows else 0.0,
        "mean_r2_da": float(_arr(rows, "r2_da").mean()) if rows else 0.0,
        "mean_gap": float((_arr(rows, "r2_da") - _arr(rows, "r2_onehot")).mean())
        if rows else 0.0,
        "n_hidden": int(sum(
            1 for r in rows if r["r2_onehot"] <= 0.05 and r["r2_da"] > 0.05
        )),
        "n_match_within_001": int(sum(
            1 for r in multi if abs(r["convex_combo_residual"]) < 0.01
        )),
        "max_residual": float(np.max(np.abs(_arr(multi, "convex_combo_residual"))))
        if multi else 0.0,
    }
    if multi:
        out["mc_mean_r2_onehot"] = float(_arr(multi, "r2_onehot").mean())
        out["mc_mean_r2_da"] = float(_arr(multi, "r2_da").mean())
        out["mc_mean_gap"] = float(
            (_arr(multi, "r2_da") - _arr(multi, "r2_onehot")).mean()
        )
        mlp_vals = [r["mlp_da_delta"] for r in multi if r["mlp_da_delta"] is not None]
        if mlp_vals:
            out["mc_mean_mlp_da"] = float(np.mean(mlp_vals))
    return out


def write_longtable(
    dataset: str, display: str, tag: str, per_seed: dict, tex_path: Path,
) -> None:
    seeds = sorted(per_seed.keys(), key=lambda x: int(x))
    label_dataset = dataset
    label_round = tag.lower()
    caption = (
        f"Full per-pair Framework D results — {display} "
        f"({tag.replace('ROUND','Round ')})."
    )
    label = f"tab:full-results-{label_dataset}-{label_round}"

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/build_dominant_axis_latex.py — do not edit by hand.")
    lines.append(r"\begin{longtable}{llccccr}")
    lines.append(rf"\caption{{{caption}}}\label{{{label}}} \\")
    lines.append(r"\toprule")
    lines.append(
        r"Purpose & Attribute & Seed & $R^2_{\text{onehot}}$ & "
        r"$R^2_{\text{DA}}$ & $\arg\max_k$ & $\Delta_{\text{MLP-DA}}$ \\"
    )
    lines.append(r"\midrule")
    lines.append(r"\endfirsthead")
    lines.append(r"\toprule")
    lines.append(
        r"Purpose & Attribute & Seed & $R^2_{\text{onehot}}$ & "
        r"$R^2_{\text{DA}}$ & $\arg\max_k$ & $\Delta_{\text{MLP-DA}}$ \\"
    )
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{r}{\textit{Continued on next page}} \\")
    lines.append(r"\endfoot")
    lines.append(r"\bottomrule")
    lines.append(r"\endlastfoot")

    # Stable ordering: by purpose then attribute as they appear in the first seed.
    first_seed = seeds[0]
    pair_order = [(r["purpose"], r["attribute"]) for r in per_seed[first_seed]["rows"]]

    for (purpose, attr) in pair_order:
        for s in seeds:
            row = next(
                (r for r in per_seed[s]["rows"]
                 if r["purpose"] == purpose and r["attribute"] == attr),
                None,
            )
            if row is None:
                continue
            mlp_str = (
                _fmt_signed(row["mlp_da_delta"])
                if row["mlp_da_delta"] is not None else "n/a"
            )
            argmax = str(row["r2_da_argmax_class"])
            lines.append(
                f"{_escape(purpose)} & {_escape(attr)} & {s} & "
                f"{_fmt(row['r2_onehot'])} & {_fmt(row['r2_da'])} & "
                f"{argmax} & {mlp_str} \\\\"
            )
        lines.append(r"\midrule")
    # remove trailing midrule before bottomrule (replace last)
    if lines[-1] == r"\midrule":
        lines.pop()
    lines.append(r"\end{longtable}")

    tex_path.parent.mkdir(parents=True, exist_ok=True)
    tex_path.write_text("\n".join(lines) + "\n")


def write_summary(per_dataset: dict[str, dict], summary_path: Path) -> None:
    lines: list[str] = []
    lines.append("# Framework D — Dominant-Axis Auditing — Latest (R5/R7) Summary")
    lines.append("")
    lines.append(
        "Re-evaluation of the **canonical** ``final.pt`` checkpoints reported in "
        "Section 5: Adult Round 5, HMDA Round 5, Diabetes Round 7 (rank-24 LoRA + "
        "per-class OvR)."
    )
    lines.append("")
    lines.append("## Per-dataset gap (mean across seed × pair)")
    lines.append("")
    lines.append(
        "| Dataset | Tag | Pair-seeds | Mean R²_onehot | Mean R²_DA | "
        "Gap (R²_DA − R²_onehot) | Hidden cases (R²_onehot ≤ 0.05 & R²_DA > 0.05) |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    total_pair_seeds = 0
    total_hidden = 0
    for ds, info in per_dataset.items():
        agg = info["aggregate"]
        lines.append(
            f"| {ds} | {info['tag']} | {agg['n_pair_seeds']} | "
            f"{_fmt(agg['mean_r2_onehot'])} | {_fmt(agg['mean_r2_da'])} | "
            f"{_fmt_signed(agg['mean_gap'])} | {agg['n_hidden']} |"
        )
        total_pair_seeds += agg["n_pair_seeds"]
        total_hidden += agg["n_hidden"]
    lines.append(
        f"| **Total** | — | {total_pair_seeds} | — | — | — | **{total_hidden}** |"
    )
    lines.append("")

    lines.append("## Multi-class subset only (where R²_DA can disagree with R²_onehot)")
    lines.append("")
    lines.append(
        "| Dataset | Tag | MC pair-seeds | Mean R²_onehot | Mean R²_DA | Gap | "
        "Mean MLP-DA Δ |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for ds, info in per_dataset.items():
        agg = info["aggregate"]
        if agg["n_multi"] == 0:
            lines.append(f"| {ds} | {info['tag']} | 0 | — | — | — | — |")
            continue
        mlp_str = _fmt_signed(agg["mc_mean_mlp_da"]) if "mc_mean_mlp_da" in agg else "—"
        lines.append(
            f"| {ds} | {info['tag']} | {agg['n_multi']} | "
            f"{_fmt(agg['mc_mean_r2_onehot'])} | {_fmt(agg['mc_mean_r2_da'])} | "
            f"{_fmt_signed(agg['mc_mean_gap'])} | {mlp_str} |"
        )
    lines.append("")

    lines.append("## Convex-combination identity validation")
    lines.append("")
    lines.append(
        "Predicts ``R²_onehot = Σ_k w_k · R²_OvR_k`` with "
        "``w_k = π_k(1−π_k) / Σ_j π_j(1−π_j)``. Per multi-class pair-seed we "
        "compare predicted vs observed R²_onehot."
    )
    lines.append("")
    lines.append(
        "| Dataset | Tag | MC pair-seeds | Match (residual < 0.01) | Max abs residual |"
    )
    lines.append("|---|---|---|---|---|")
    total_mc = 0
    total_match = 0
    for ds, info in per_dataset.items():
        agg = info["aggregate"]
        n_mc = agg["n_multi"]
        n_match = agg["n_match_within_001"]
        max_res = agg["max_residual"]
        lines.append(
            f"| {ds} | {info['tag']} | {n_mc} | {n_match}/{n_mc} | "
            f"{_fmt(max_res)} |"
        )
        total_mc += n_mc
        total_match += n_match
    pct = (100.0 * total_match / total_mc) if total_mc else 0.0
    lines.append(
        f"| **Total** | — | {total_mc} | "
        f"**{total_match}/{total_mc} ({pct:.1f}%)** | — |"
    )
    lines.append("")

    summary_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    per_dataset: dict[str, dict] = {}
    for spec in INPUTS:
        ds = spec["dataset"]
        tag = spec["tag"]
        data = load_dataset(ds, tag)
        # JSON keys may be strings (json.dumps converts int seed keys); normalize.
        per_seed_raw = data["per_seed"]
        per_seed: dict = {int(s): per_seed_raw[s] for s in per_seed_raw}
        agg = aggregate(per_seed)
        per_dataset[ds] = {"tag": tag, "per_seed": per_seed, "aggregate": agg}

        tex_path = TABLES_DIR / spec["tex_name"]
        write_longtable(ds, spec["display"], tag, per_seed, tex_path)
        print(f"wrote {tex_path}")

    summary_path = ROOT / "results" / "V2_DOMINANT_AXIS_LATEST_SUMMARY.md"
    write_summary(per_dataset, summary_path)
    print(f"wrote {summary_path}")

    # Console summary
    print("\n=== AGGREGATE ===")
    for ds, info in per_dataset.items():
        agg = info["aggregate"]
        print(
            f"  {ds:9s} ({info['tag']}): n={agg['n_pair_seeds']:2d}  "
            f"mean R²_onehot={agg['mean_r2_onehot']:.4f}  "
            f"mean R²_DA={agg['mean_r2_da']:.4f}  "
            f"gap={agg['mean_gap']:+.4f}  "
            f"hidden={agg['n_hidden']}  "
            f"MC convex-match={agg['n_match_within_001']}/{agg['n_multi']}  "
            f"max-res={agg['max_residual']:.4f}"
        )


if __name__ == "__main__":
    main()
