#!/usr/bin/env python3
"""Build paper-body/tables/single_purpose_baselines.tex.

Reads PCRL Framework D numbers (first purpose only) from
``results/v2_<dataset>_<TAG>/dominant_axis_audit.json`` and PCRL task
accuracies from ``results/v2_<dataset>_<TAG>/per_seed_results.json``,
then merges with LAFTR/INLP results from
``results/baselines_singlepurpose/{dataset}_{method}_s{seed}.json``.

Emits two stacked LaTeX tables in one file:
  • Per-attribute R²_onehot and R²_DA (lower = stronger protection)
  • Per-dataset task accuracy (higher = better)

Cells are bolded where a baseline beats PCRL on the corresponding metric.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
TABLES_DIR = ROOT / "paper-body" / "tables"
BASELINES_DIR = ROOT / "results" / "baselines_singlepurpose"

# (dataset, PCRL tag, first-purpose name, task name, attrs in display order)
DATASETS = [
    {
        "id": "adult", "display": "Adult", "tag": "ROUND5",
        "purpose": "income_prediction", "task": "income",
        "attrs": ["race", "sex"],
    },
    {
        "id": "hmda", "display": "HMDA", "tag": "ROUND5",
        "purpose": "underwriting", "task": "loan_decision",
        "attrs": ["race", "ethnicity"],
    },
    {
        "id": "diabetes", "display": "Diabetes", "tag": "ROUND7",
        "purpose": "billing_audit", "task": "primary_diagnosis_category",
        "attrs": ["race", "gender"],
    },
]

METHODS = ["pcrl", "laftr", "inlp"]
METHOD_DISPLAY = {"pcrl": "PCRL", "laftr": "LAFTR", "inlp": "INLP"}


def _esc(s: str) -> str:
    return s.replace("_", r"\_")


def load_pcrl(ds: dict) -> dict:
    """Per-attribute mean ± std of R²_onehot, R²_DA + task_acc."""
    audit_path = ROOT / "results" / f"v2_{ds['id']}_{ds['tag']}" / "dominant_axis_audit.json"
    psr_path = ROOT / "results" / f"v2_{ds['id']}_{ds['tag']}" / "per_seed_results.json"
    audit = json.loads(audit_path.read_text())
    psr = json.loads(psr_path.read_text())

    out: dict = {"r2_onehot": {}, "r2_da": {}, "task_acc": (None, None)}
    for attr in ds["attrs"]:
        r2o, r2da = [], []
        for seed_str, blob in audit["per_seed"].items():
            for row in blob["rows"]:
                if row["purpose"] == ds["purpose"] and row["attribute"] == attr:
                    r2o.append(row["r2_onehot"])
                    r2da.append(row["r2_da"])
        out["r2_onehot"][attr] = (float(np.mean(r2o)), float(np.std(r2o)))
        out["r2_da"][attr] = (float(np.mean(r2da)), float(np.std(r2da)))

    # Task accuracy from per_seed_results.json — task_accuracies dict per seed
    accs = []
    for s in psr["per_seed"]:
        ta = s["task_accuracies"]
        if ds["task"] in ta:
            accs.append(ta[ds["task"]])
    if accs:
        out["task_acc"] = (float(np.mean(accs)), float(np.std(accs)))
    return out


def load_baseline(ds: dict, method: str) -> dict:
    """Aggregate per-attribute R² and task_acc across seeds for one baseline."""
    out: dict = {"r2_onehot": {}, "r2_da": {}, "task_acc": (None, None)}
    per_attr_ro: dict[str, list[float]] = {a: [] for a in ds["attrs"]}
    per_attr_rda: dict[str, list[float]] = {a: [] for a in ds["attrs"]}
    accs: list[float] = []
    for seed in (0, 1, 2):
        path = BASELINES_DIR / f"{ds['id']}_{method}_s{seed}.json"
        if not path.exists():
            continue
        rec = json.loads(path.read_text())
        for attr in ds["attrs"]:
            stats = rec["metrics"]["per_attr"].get(attr)
            if stats is None:
                continue
            per_attr_ro[attr].append(stats["r2_onehot"])
            per_attr_rda[attr].append(stats["r2_da"])
        accs.append(rec["metrics"]["task_acc"])

    for attr in ds["attrs"]:
        if per_attr_ro[attr]:
            out["r2_onehot"][attr] = (float(np.mean(per_attr_ro[attr])),
                                      float(np.std(per_attr_ro[attr])))
            out["r2_da"][attr] = (float(np.mean(per_attr_rda[attr])),
                                  float(np.std(per_attr_rda[attr])))
    if accs:
        out["task_acc"] = (float(np.mean(accs)), float(np.std(accs)))
    return out


def fmt_pm(stats: tuple[float | None, float | None], places: int = 4,
           bold: bool = False) -> str:
    if stats is None or stats[0] is None:
        return "—"
    m, s = stats
    body = f"{m:.{places}f} $\\pm$ {s:.{places}f}"
    return r"\textbf{" + body + "}" if bold else body


def build_r2_table(rows_by_method: dict[str, dict]) -> str:
    """rows_by_method[method][dataset_id] -> dict of metrics."""
    L: list[str] = []
    L.append(r"% Auto-generated by scripts/build_single_purpose_baselines_latex.py — do not edit by hand.")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption{Single-purpose baselines vs.\ PCRL on the first purpose of each dataset"
             r" (Adult/\texttt{income\_prediction}, HMDA/\texttt{underwriting},"
             r" Diabetes/\texttt{billing\_audit}). $R^2_{\text{onehot}}$ and $R^2_{\text{DA}}$"
             r" are reported as mean $\pm$ std over 3 seeds. Lower is better."
             r" \textbf{Bold} cells indicate a baseline beats PCRL on that metric"
             r" (i.e., achieves lower $R^2$).}")
    L.append(r"\label{tab:single-purpose-baselines-r2}")
    L.append(r"\small")
    L.append(r"\begin{tabular}{llccc|ccc}")
    L.append(r"\toprule")
    L.append(r" & & \multicolumn{3}{c|}{$R^2_{\text{onehot}}$} & \multicolumn{3}{c}{$R^2_{\text{DA}}$} \\")
    L.append(r" Dataset & Attr & PCRL & LAFTR & INLP & PCRL & LAFTR & INLP \\")
    L.append(r"\midrule")
    for ds in DATASETS:
        for attr in ds["attrs"]:
            pcrl_o = rows_by_method["pcrl"][ds["id"]]["r2_onehot"].get(attr)
            laftr_o = rows_by_method["laftr"][ds["id"]]["r2_onehot"].get(attr)
            inlp_o = rows_by_method["inlp"][ds["id"]]["r2_onehot"].get(attr)
            pcrl_d = rows_by_method["pcrl"][ds["id"]]["r2_da"].get(attr)
            laftr_d = rows_by_method["laftr"][ds["id"]]["r2_da"].get(attr)
            inlp_d = rows_by_method["inlp"][ds["id"]]["r2_da"].get(attr)

            laftr_o_b = laftr_o is not None and pcrl_o is not None and laftr_o[0] < pcrl_o[0]
            inlp_o_b = inlp_o is not None and pcrl_o is not None and inlp_o[0] < pcrl_o[0]
            laftr_d_b = laftr_d is not None and pcrl_d is not None and laftr_d[0] < pcrl_d[0]
            inlp_d_b = inlp_d is not None and pcrl_d is not None and inlp_d[0] < pcrl_d[0]

            L.append(
                f"{ds['display']} & {_esc(attr)} & "
                f"{fmt_pm(pcrl_o)} & {fmt_pm(laftr_o, bold=laftr_o_b)} & {fmt_pm(inlp_o, bold=inlp_o_b)} & "
                f"{fmt_pm(pcrl_d)} & {fmt_pm(laftr_d, bold=laftr_d_b)} & {fmt_pm(inlp_d, bold=inlp_d_b)} \\\\"
            )
        L.append(r"\midrule")
    if L[-1] == r"\midrule":
        L.pop()
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    return "\n".join(L)


def build_task_table(rows_by_method: dict[str, dict]) -> str:
    L: list[str] = []
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption{Task accuracy on the first-purpose task. Mean $\pm$ std over 3 seeds."
             r" \textbf{Bold} cells indicate a baseline beats PCRL on task accuracy.}")
    L.append(r"\label{tab:single-purpose-baselines-task}")
    L.append(r"\small")
    L.append(r"\begin{tabular}{llccc}")
    L.append(r"\toprule")
    L.append(r" Dataset & Task & PCRL & LAFTR & INLP \\")
    L.append(r"\midrule")
    for ds in DATASETS:
        pcrl_t = rows_by_method["pcrl"][ds["id"]]["task_acc"]
        laftr_t = rows_by_method["laftr"][ds["id"]]["task_acc"]
        inlp_t = rows_by_method["inlp"][ds["id"]]["task_acc"]
        laftr_b = laftr_t[0] is not None and pcrl_t[0] is not None and laftr_t[0] > pcrl_t[0]
        inlp_b = inlp_t[0] is not None and pcrl_t[0] is not None and inlp_t[0] > pcrl_t[0]
        L.append(
            f"{ds['display']} & {_esc(ds['task'])} & "
            f"{fmt_pm(pcrl_t)} & {fmt_pm(laftr_t, bold=laftr_b)} & {fmt_pm(inlp_t, bold=inlp_b)} \\\\"
        )
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    return "\n".join(L)


def main() -> None:
    rows_by_method: dict[str, dict] = {m: {} for m in METHODS}
    for ds in DATASETS:
        rows_by_method["pcrl"][ds["id"]] = load_pcrl(ds)
        rows_by_method["laftr"][ds["id"]] = load_baseline(ds, "laftr")
        rows_by_method["inlp"][ds["id"]] = load_baseline(ds, "inlp")

    body = build_r2_table(rows_by_method) + "\n\n" + build_task_table(rows_by_method) + "\n"
    out_path = TABLES_DIR / "single_purpose_baselines.tex"
    out_path.write_text(body)
    print(f"wrote {out_path}")
    print(body)


if __name__ == "__main__":
    main()
