"""Aggregate three pipelines side-by-side: Round 5/7 baseline vs erase-layer
pilot λ_vicreg=1.0 vs erase-layer pilot λ_vicreg=5.0.

Reads (per dataset):
    results/v2_adult_ROUND5/{summary,per_seed_results}.json     # baseline
    results/v2_hmda_ROUND5/{...}
    results/v2_diabetes_ROUND7/{...}

    results/v2_adult_ERASE_PILOT/{...}                          # λ=1.0
    results/v2_hmda_ERASE_PILOT/{...}
    results/v2_diabetes_ERASE_PILOT/{...}

    results/v2_adult_ERASE_VICREG5/{...}                        # λ=5.0
    results/v2_hmda_ERASE_VICREG5/{...}
    results/v2_diabetes_ERASE_VICREG5/{...}

Writes:
    results/rebuttal/erase_layer_vicreg_sweep/comparison_table.tex
    results/rebuttal/erase_layer_vicreg_sweep/comparison.json
    results/rebuttal/erase_layer_vicreg_sweep/HEADLINE.txt
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "results" / "rebuttal" / "erase_layer_vicreg_sweep"

PER_DIM_STD_MIN = 0.5
EFF_RANK_MIN = 2.0
R2_THRESHOLD = 0.05


def _load(p: Path) -> dict[str, Any]:
    if not p.is_file():
        raise FileNotFoundError(f"missing: {p}")
    with open(p) as fh:
        return json.load(fh)


def _per_seed_list(d: dict) -> list[dict]:
    return d["per_seed"] if "per_seed" in d else d


def _strict_pass(per_seed: list[dict]) -> tuple[int, int]:
    s, n = 0, 0
    for seed in per_seed:
        for c in seed["attribute_results"]:
            n += 1
            if c["linear_r2"] <= R2_THRESHOLD:
                s += 1
    return s, n


def _cleanly_compliant(per_seed: list[dict]) -> int:
    out = 0
    for seed in per_seed:
        h = seed.get("per_purpose_health", {})
        for c in seed["attribute_results"]:
            ph = h.get(c["purpose"], {})
            if (c["linear_r2"] <= R2_THRESHOLD
                    and ph.get("per_dim_std_mean", 0.0) >= PER_DIM_STD_MIN
                    and ph.get("effective_rank", 0.0) >= EFF_RANK_MIN):
                out += 1
    return out


def _health(per_seed: list[dict]) -> tuple[float, float]:
    stds: list[float] = []
    ranks: list[float] = []
    for seed in per_seed:
        for ph in seed.get("per_purpose_health", {}).values():
            stds.append(ph.get("per_dim_std_mean", 0.0))
            ranks.append(ph.get("effective_rank", 0.0))
    if not stds:
        return float("nan"), float("nan")
    return sum(stds) / len(stds), sum(ranks) / len(ranks)


def _mean_max_r2(per_seed: list[dict]) -> tuple[float, float]:
    rs = [c["linear_r2"] for s in per_seed for c in s["attribute_results"]]
    if not rs:
        return float("nan"), float("nan")
    return sum(rs) / len(rs), max(rs)


def _arm(per_seed_path: Path) -> dict[str, Any]:
    """Compute the metric block for one pipeline arm on one dataset."""
    per = _load(per_seed_path)
    seeds = _per_seed_list(per)
    strict, n = _strict_pass(seeds)
    clean = _cleanly_compliant(seeds)
    std_mean, rank_mean = _health(seeds)
    r2_mean, r2_max = _mean_max_r2(seeds)
    return {
        "strict_pass": strict,
        "n_cells": n,
        "cleanly_compliant": clean,
        "per_dim_std_mean": std_mean,
        "eff_rank_mean": rank_mean,
        "r2_mean": r2_mean,
        "r2_max": r2_max,
    }


def _row(dataset: str, base_tag: str) -> dict[str, Any]:
    base_path = REPO_ROOT / "results" / f"v2_{dataset}_{base_tag}" / "per_seed_results.json"
    pilot_path = REPO_ROOT / "results" / f"v2_{dataset}_ERASE_PILOT" / "per_seed_results.json"
    vicreg5_path = REPO_ROOT / "results" / f"v2_{dataset}_ERASE_VICREG5" / "per_seed_results.json"
    return {
        "dataset": dataset,
        "base_tag": base_tag,
        "baseline": _arm(base_path),
        "pilot_lambda_vicreg_1": _arm(pilot_path),
        "pilot_lambda_vicreg_5": _arm(vicreg5_path),
    }


def _fmt_pass(arm: dict) -> str:
    return f"{arm['strict_pass']}/{arm['n_cells']}"


def _fmt_clean(arm: dict) -> str:
    return f"{arm['cleanly_compliant']}/{arm['n_cells']}"


def _render_tex(rows: list[dict]) -> str:
    L: list[str] = []
    L.append(r"% Auto-generated by scripts/build_erase_pilot_vicreg_comparison.py")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\small")
    L.append(r"\caption{Erase-layer pilot $\lambda_{\text{vicreg}}$ sweep. "
             r"\textit{Baseline}: submitted Round 5/7 pipeline (LoRA-inside-LEACE). "
             r"\textit{Pilot $\lambda{=}1.0$}: erase-layer architecture ported from \S5.5 vision. "
             r"\textit{Pilot $\lambda{=}5.0$}: same architecture, VICReg outer-multiplier $\times 5$. "
             r"\textit{Strict pass}: $R^2(h_p, A) \leq 0.05$. "
             r"\textit{Cleanly compliant}: strict pass $\wedge$ per-dim std $\geq 0.5$ "
             r"$\wedge$ eff.~rank $\geq 2.0$.}")
    L.append(r"\label{tab:erase_vicreg_sweep}")
    L.append(r"\begin{tabular}{l l r r r r}")
    L.append(r"\toprule")
    L.append(r" & & Strict & Clean & per-dim std & eff.~rank \\")
    L.append(r"\midrule")
    grand: dict[str, dict[str, int]] = {
        "baseline":              {"strict": 0, "clean": 0, "n": 0},
        "pilot_lambda_vicreg_1": {"strict": 0, "clean": 0, "n": 0},
        "pilot_lambda_vicreg_5": {"strict": 0, "clean": 0, "n": 0},
    }
    for r in rows:
        ds = r["dataset"].title()
        L.append(rf"\multirow{{3}}{{*}}{{{ds}}} & Baseline ({r['base_tag']}) & "
                 rf"{_fmt_pass(r['baseline'])} & {_fmt_clean(r['baseline'])} & "
                 rf"{r['baseline']['per_dim_std_mean']:.3f} & {r['baseline']['eff_rank_mean']:.2f} \\")
        L.append(rf" & Erase $\lambda{{=}}1.0$ & "
                 rf"{_fmt_pass(r['pilot_lambda_vicreg_1'])} & {_fmt_clean(r['pilot_lambda_vicreg_1'])} & "
                 rf"{r['pilot_lambda_vicreg_1']['per_dim_std_mean']:.3f} & {r['pilot_lambda_vicreg_1']['eff_rank_mean']:.2f} \\")
        L.append(rf" & Erase $\lambda{{=}}5.0$ & "
                 rf"{_fmt_pass(r['pilot_lambda_vicreg_5'])} & {_fmt_clean(r['pilot_lambda_vicreg_5'])} & "
                 rf"{r['pilot_lambda_vicreg_5']['per_dim_std_mean']:.3f} & {r['pilot_lambda_vicreg_5']['eff_rank_mean']:.2f} \\")
        L.append(r"\midrule")
        for arm in grand:
            grand[arm]["strict"] += r[arm]["strict_pass"]
            grand[arm]["clean"] += r[arm]["cleanly_compliant"]
            grand[arm]["n"] += r[arm]["n_cells"]
    L.append(rf"\multirow{{3}}{{*}}{{\textbf{{Total}}}} & Baseline & "
             rf"{grand['baseline']['strict']}/{grand['baseline']['n']} & "
             rf"{grand['baseline']['clean']}/{grand['baseline']['n']} & --- & --- \\")
    L.append(rf" & Erase $\lambda{{=}}1.0$ & "
             rf"{grand['pilot_lambda_vicreg_1']['strict']}/{grand['pilot_lambda_vicreg_1']['n']} & "
             rf"{grand['pilot_lambda_vicreg_1']['clean']}/{grand['pilot_lambda_vicreg_1']['n']} & --- & --- \\")
    L.append(rf" & Erase $\lambda{{=}}5.0$ & "
             rf"{grand['pilot_lambda_vicreg_5']['strict']}/{grand['pilot_lambda_vicreg_5']['n']} & "
             rf"{grand['pilot_lambda_vicreg_5']['clean']}/{grand['pilot_lambda_vicreg_5']['n']} & --- & --- \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    return "\n".join(L) + "\n"


def _render_headline(rows: list[dict]) -> str:
    L = ["ERASE-LAYER λ_vicreg SWEEP",
         "=" * 60,
         "  3-way comparison: Round 5/7 baseline vs Erase λ=1.0 vs Erase λ=5.0",
         ""]
    grand_strict = {"b": 0, "p1": 0, "p5": 0}
    grand_clean = {"b": 0, "p1": 0, "p5": 0}
    grand_n = 0
    for r in rows:
        b, p1, p5 = r["baseline"], r["pilot_lambda_vicreg_1"], r["pilot_lambda_vicreg_5"]
        L.append(f"  {r['dataset']:10s}")
        L.append(f"    strict   base {_fmt_pass(b)}  pilot1 {_fmt_pass(p1)}  pilot5 {_fmt_pass(p5)}")
        L.append(f"    clean    base {_fmt_clean(b)}  pilot1 {_fmt_clean(p1)}  pilot5 {_fmt_clean(p5)}")
        L.append(f"    std mean base {b['per_dim_std_mean']:.3f}  pilot1 {p1['per_dim_std_mean']:.3f}  pilot5 {p5['per_dim_std_mean']:.3f}")
        L.append(f"    rank mean base {b['eff_rank_mean']:.2f}  pilot1 {p1['eff_rank_mean']:.2f}  pilot5 {p5['eff_rank_mean']:.2f}")
        L.append("")
        grand_strict["b"] += b["strict_pass"]; grand_strict["p1"] += p1["strict_pass"]; grand_strict["p5"] += p5["strict_pass"]
        grand_clean["b"] += b["cleanly_compliant"]; grand_clean["p1"] += p1["cleanly_compliant"]; grand_clean["p5"] += p5["cleanly_compliant"]
        grand_n += b["n_cells"]
    L.append(f"  TOTAL  strict base {grand_strict['b']}/{grand_n}  "
             f"pilot1 {grand_strict['p1']}/{grand_n}  pilot5 {grand_strict['p5']}/{grand_n}")
    L.append(f"  TOTAL  clean  base {grand_clean['b']}/{grand_n}  "
             f"pilot1 {grand_clean['p1']}/{grand_n}  pilot5 {grand_clean['p5']}/{grand_n}")
    return "\n".join(L) + "\n"


def main() -> None:
    rows = [
        _row("adult", "ROUND5"),
        _row("hmda", "ROUND5"),
        _row("diabetes", "ROUND7"),
    ]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "comparison_table.tex").write_text(_render_tex(rows))
    headline = _render_headline(rows)
    (OUT_DIR / "HEADLINE.txt").write_text(headline)
    (OUT_DIR / "comparison.json").write_text(json.dumps({
        "thresholds": {
            "r2": R2_THRESHOLD,
            "per_dim_std_min": PER_DIM_STD_MIN,
            "eff_rank_min": EFF_RANK_MIN,
        },
        "rows": rows,
    }, indent=2))
    print(headline)
    print(f"\nwrote: {OUT_DIR / 'comparison_table.tex'}")
    print(f"wrote: {OUT_DIR / 'HEADLINE.txt'}")
    print(f"wrote: {OUT_DIR / 'comparison.json'}")


if __name__ == "__main__":
    main()
