#!/usr/bin/env python3
"""Render bound_numerical_results.json into paper artifacts:
   tightness_table.tex, bound_vs_observed_plot.pdf, PAPER_PASTE.md, HEADLINE.txt.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent / "results" / "quantitative_t2_binding"
DATA = json.loads((ROOT / "bound_numerical_results.json").read_text())


def fmt(x: float, prec: int = 4) -> str:
    if isinstance(x, float) and (np.isnan(x) or np.isinf(x)):
        return "--"
    return f"{x:.{prec}f}"


# ── tightness_table.tex ───────────────────────────────────────────────
def render_table():
    lines = [
        "% Auto-generated by scripts/quantitative_t2_render.py.",
        "% Do not edit by hand; rerun the renderer if numbers change.",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r" & $\sum_i \gamma_i$ & $\sum_i \delta_i$ "
        r"& $B_{\rm tight}$ & $\sum_i {\rm Err}_i$ & ratio \\",
        r"\midrule",
    ]
    label_map = {"adult": "Adult (R5)", "hmda": "HMDA (R5)", "diabetes": "Diabetes (R7)"}
    for s in DATA["summary"]:
        ds = s["dataset"]
        lines.append(
            f"{label_map[ds]} "
            f"& {fmt(s['sum_gamma_loose_mean'])} "
            f"& {fmt(s['sum_delta_loose_mean'])} "
            f"& {fmt(s['sum_tight_bound_mean'])} "
            f"& {fmt(s['sum_err_mean'])} "
            f"& {fmt(s['ratio_tight_mean'], 1)}"
            r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    (ROOT / "tightness_table.tex").write_text("\n".join(lines) + "\n")
    print("→ tightness_table.tex")


# ── bound_vs_observed_plot.pdf ────────────────────────────────────────
def render_plot():
    fig, ax = plt.subplots(figsize=(5.0, 4.5))
    color_map = {"adult": "#1f77b4", "hmda": "#d62728", "diabetes": "#2ca02c"}
    label_map = {"adult": "Adult (R5)", "hmda": "HMDA (R5)", "diabetes": "Diabetes (R7)"}
    seen = set()
    xs_all, ys_all = [], []
    for r in DATA["per_dataset_seed"]:
        x = max(r["sum_tight_bound"], 1e-6)
        y = r["sum_err"]
        xs_all.append(x); ys_all.append(y)
        ds = r["dataset"]
        ax.scatter(
            x, y, c=color_map[ds], s=70, alpha=0.85,
            edgecolors="black", linewidths=0.5,
            label=label_map[ds] if ds not in seen else None,
        )
        seen.add(ds)
    lo = min(xs_all) * 0.5
    hi = max(ys_all) * 1.5
    ax.plot([lo, hi], [lo, hi], "k--", linewidth=1, alpha=0.6, label="$y=x$ (tight)")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_xlabel(r"Predicted bound  $B_{\rm tight} = \sum_i \max_{a,a'} "
                  r"\min(p_a, p_{a'})\,(d_{\rm TV}(Y_i)-d_{\rm TV}(\widehat{Y}_i))$")
    ax.set_ylabel(r"Observed  $\sum_i {\rm Err}_i$")
    ax.set_title("PCRL: observed total error vs. d$_{\\rm TV}$ corollary lower bound\n"
                 "(per-seed, attribute = race)")
    ax.legend(loc="lower right", fontsize=8)
    ax.grid(True, which="both", alpha=0.3)
    fig.tight_layout()
    fig.savefig(ROOT / "bound_vs_observed_plot.pdf", bbox_inches="tight")
    plt.close(fig)
    print("→ bound_vs_observed_plot.pdf")


# ── PAPER_PASTE.md ────────────────────────────────────────────────────
def render_paper_paste():
    by_ds = {s["dataset"]: s for s in DATA["summary"]}
    a, h, d = by_ds["adult"], by_ds["hmda"], by_ds["diabetes"]

    lines = [
        "# PAPER_PASTE — d_TV pair-witness corollary, PCRL Round 5/7",
        "",
        "## 1. Drop-in corollary for §3 (Multi-Purpose Impossibility)",
        "",
        "See `corollary.tex` in this directory. Three-sentence proof, no factor",
        "of ½, no Pinsker chain, attribute-pair witness convention.",
        "",
        "## 2. Suggested integration sentence for §5.4 worked example",
        "",
        "**Honest framing (recommended).** The pair-witness corollary's tight",
        "lower bound $B_{\\rm tight} = \\sum_i \\max_{a,a'}\\min(p_a,p_{a'})"
        "(d_{\\rm TV}(Y_i\\mid A=a, Y_i\\mid A=a')-d_{\\rm TV}(\\widehat Y_i\\mid A=a,"
        "\\widehat Y_i\\mid A=a'))$ is",
        "satisfied on every seed of all three datasets",
        f"(Adult: {a['sum_tight_bound_mean']:.3f} bound vs.\\ {a['sum_err_mean']:.3f} observed; ",
        f"HMDA: {h['sum_tight_bound_mean']:.3f} vs.\\ {h['sum_err_mean']:.3f}; ",
        f"Diabetes: {d['sum_tight_bound_mean']:.3f} vs.\\ {d['sum_err_mean']:.3f}). ",
        "Theorem~\\ref{thm:multi-purpose-impossibility}'s d$_{\\rm TV}$ form is",
        "qualitatively confirmed---the bound is positive and respected---but",
        "the gap (a factor of",
        f"{a['ratio_tight_mean']:.0f}\\,$\\times$ on Adult, "
        f"{h['ratio_tight_mean']:.0f}\\,$\\times$ on HMDA, "
        f"{d['ratio_tight_mean']:.0f}\\,$\\times$ on Diabetes)",
        "shows that the demographic-shift component captured by the corollary",
        "is *not* the binding constraint on PCRL. The binding source of",
        "$\\sum_i {\\rm Err}_i$ on these benchmarks is irreducible task noise",
        "(majority-class baselines for the multi-class tasks: HMDA loan-amount",
        "$\\approx0.50$, Diabetes primary-diagnosis $\\approx0.32$); the corollary",
        "predicts the *demographic floor* on error, not its level.",
        "",
        "## 3. Recommended placement",
        "",
        "- **Theorem 2 (d$_{\\rm TV}$ corollary):** add to §3 as Corollary~1, after",
        "  the existing mutual-information form. Use the proof in `corollary.tex`.",
        "- **§5.4 worked example:** insert the integration sentence above and",
        "  cite `tightness_table.tex` (this directory) for numerics. Plot",
        "  `bound_vs_observed_plot.pdf` is optional---it visualizes the gap on",
        "  log-log axes, which can either underline the qualitative agreement or",
        "  invite criticism, depending on framing.",
        "- **Limitations §:** acknowledge that the d$_{\\rm TV}$ floor is not",
        "  the binding constraint at PCRL's operating point. The corollary is a",
        "  *necessity* bound, not a *sufficiency* certificate of optimality.",
        "",
        "## 4. Don't claim",
        "",
        "Avoid \"PCRL achieves the impossibility bound on Adult within 10\\%\".",
        f"The actual ratio is {a['ratio_tight_mean']:.0f}\\,$\\times$",
        "on Adult; that's a clear gap, not a tight match. The honest claim is:",
        "\"PCRL's observed $\\sum_i{\\rm Err}_i$ respects Corollary 1 with",
        "$B_{\\rm tight}>0$ on every seed; the gap reflects task-noise dominance.\"",
        "",
        "## 5. Numbers (mean over 3 seeds)",
        "",
        "| Dataset | $\\sum\\gamma_i$ | $\\sum\\delta_i$ | $B_{\\rm tight}$ | "
        "$\\sum {\\rm Err}_i$ | ratio |",
        "|---|---|---|---|---|---|",
    ]
    label_map = {"adult": "Adult (R5)", "hmda": "HMDA (R5)", "diabetes": "Diabetes (R7)"}
    for s in DATA["summary"]:
        ds = s["dataset"]
        lines.append(
            f"| {label_map[ds]} "
            f"| {s['sum_gamma_loose_mean']:.4f} "
            f"| {s['sum_delta_loose_mean']:.4f} "
            f"| {s['sum_tight_bound_mean']:.4f} "
            f"| {s['sum_err_mean']:.4f} "
            f"| {s['ratio_tight_mean']:.1f}× |"
        )

    lines.extend([
        "",
        "Per-seed, per-purpose witness data: `bound_numerical_results.json`.",
        "",
        "## 6. Why the loose form is reported separately",
        "",
        "The user's original draft of the corollary used",
        "$\\gamma_i := \\max_{a,a'}\\min(p_a,p_{a'})\\,d_{\\rm TV}(Y_i)$ and",
        "$\\delta_i := \\max_{a,a'}d_{\\rm TV}(\\widehat Y_i)$ as *independent* maxima.",
        "Subtracting them gives $\\sum\\gamma_i-\\sum\\delta_i$, which is",
        f"negative on every dataset (Adult: {a['bound_loose_mean']:+.3f}; "
        f"HMDA: {h['bound_loose_mean']:+.3f}; "
        f"Diabetes: {d['bound_loose_mean']:+.3f}). ",
        "The proof actually delivers the same-pair (\"tight\") form via",
        "$\\max_{a,a'}\\min(p_a,p_{a'})(d_{\\rm TV}(Y_i)-d_{\\rm TV}(\\widehat Y_i))",
        "\\le {\\rm Err}_i$, which is what `corollary.tex` states. Reporting",
        "both makes the gap source obvious---it is the witness-pair coupling,",
        "not the data---so reviewers don't have to take the tighter version on",
        "faith.",
        "",
    ])
    (ROOT / "PAPER_PASTE.md").write_text("\n".join(lines))
    print("→ PAPER_PASTE.md")


# ── HEADLINE.txt ──────────────────────────────────────────────────────
def render_headline():
    by_ds = {s["dataset"]: s for s in DATA["summary"]}
    a, h, d = by_ds["adult"], by_ds["hmda"], by_ds["diabetes"]
    lines = [
        "Theorem 2 d_TV corollary: VERIFIED but NOT BINDING on PCRL R5/R7.",
        f"  Adult    bound={a['sum_tight_bound_mean']:.4f}  err={a['sum_err_mean']:.4f}  "
        f"ratio={a['ratio_tight_mean']:.1f}x",
        f"  HMDA     bound={h['sum_tight_bound_mean']:.4f}  err={h['sum_err_mean']:.4f}  "
        f"ratio={h['ratio_tight_mean']:.1f}x",
        f"  Diabetes bound={d['sum_tight_bound_mean']:.4f}  err={d['sum_err_mean']:.4f}  "
        f"ratio={d['ratio_tight_mean']:.1f}x",
        "Corollary holds on all 9 (dataset,seed) cells; gap reflects task-noise dominance.",
    ]
    (ROOT / "HEADLINE.txt").write_text("\n".join(lines) + "\n")
    print("→ HEADLINE.txt")


if __name__ == "__main__":
    render_table()
    render_plot()
    render_paper_paste()
    render_headline()
